Primer objetivo 0
abbonno/healthScheduler pull request #1
Opened 2024-09-24 15:45 UTC by abbonno

¿Se trata de un problema real del que se tenga conocimiento personal?
Sí, mi tío es enfermero y me suele hablar de cómo tienen problemas a la hora de completar los horarios de trabajando respetando condiciones de trabajo adecuadas como horas de descanso, vacaciones, días de baja...
¿Se trata de un problema que no necesite ningún servicio o aparato externo para funcionar?
No es necesario emplear ninguna api, servicio o dispositivo adicionales.
¿La solución requiere una cierta cantidad de lógica de negocio, en vez de solucionarse sólo almacenando y buscando?
Sí, optimizar turnos y horarios respetando las condiciones dadas requiere más del programa a crear para solucionar el problema que consulta y almacén de datos.
¿Tienes todos los datos necesarios para poder resolver el problema?
Los datos vienen proporcionados por el cliente, mi tío en este caso, que conoce de primera mano cada uno de los factores a tener en cuenta, por lo que sí.

2024-09-24 16:20 UTC, abbonno commented
Buenas tardes profesor, al hacer el test me ha salido este problema
Error: 🍋💥❌ El título del PR en tu repositorio debe empezar con «[IV-», este dice «Primer objetivo 0»
He cambiado ya el título pero no me lo da por bueno, ¿qué debo hacer?

2024-09-27 11:40 UTC, abbonno commented
@JJ

2024-09-27 18:03 UTC, JJ commented
No basta con eliminar la línea que se refiere a la configuración del repo; tienes que hacerlo. Mira en [la explicación](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n) en qué consiste esa configuración y lo que hay que hacer con ella.

2024-10-02 17:08 UTC, abbonno commented
@JJ

2024-10-02 17:48 UTC, JJ requested changes
¿Te parece que el pantallazo de "crear un repositorio" corresponda a "configuración"? Por favor, consulta en [explicación](https://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n) lo que *sí* es configuración (y también por qué es necesario que lo pongáis aquí)

2024-10-02 17:48 UTC, JJ commented on README.md
> + - [Licencia](./docs/LICENSE)
Ni la licencia es parte de la configuración ni debe estar en el directorio donde la has puesto.
`LICENSE` debe ser parte del repositorio, sin embargo. Lo correcto es que añadas el fichero en MAIN y hagas un rebase de esta rama (simplemente edita el PR pulsando en Edit)

2024-10-02 17:48 UTC, JJ commented on README.md
> +Desarrollador: tu problema es que en tu trabajo necesitáis cubrir todas las horas pero pueden haber cambios imprevistos y no tenéis una manera de comunicaros sencillamente para satisfacer las necesid
Creo que no está en ningún lado en el guión el que el desarrollador tenga que decir nada, salvo en el caso en que sea dudosa la lógica de negocio que se deba usar.

2024-10-02 17:48 UTC, JJ commented on README.md
> +Cliente: soy un enfermero, mi problema es que no hay organización entre mis compañeros y yo a la hora de cumplir con horarios de guardia, sustituir bajas y en general cambiar turnos.
Tienes que ser un poco más preciso en el problema y no suponer que recuerdo todo lo que me has contado. Por favor, cuenta todo el contexto que sea necesario.

2024-10-03 10:31 UTC, abbonno commented
@JJ

2024-10-03 11:13 UTC, JJ approved these changes
👍

2024-10-03 11:16 UTC, merged