[IV-24-25] objetivo 1 design thinking
abbonno/healthScheduler pull request #2
Opened 2024-10-10 11:14 UTC by abbonno

* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
Sí, resultan una hoja de ruta para realizar los primeros pasos.
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
Sí, describe bien el primer producto mínimo viable para que se pueda entender por quienes vayan a trabajar en nuestro proyecto.
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
Sí.
* [ ] ¿El milestone 0 es mínimo *y* viable?
Sí.
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
Sí.
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

2024-10-10 18:44 UTC, eigenric commented
Buenas! Se me ha asignado revisar tu PR. A continuación realizaré algunos comentarios.

2024-10-10 20:19 UTC, eigenric commented on docs/milestones.md
> +## Milestone 0
Los nombres de los Milestones deberían estar en consonancia con los creados en el apartado de Github y definir un producto mínimo viable.  Para la viabilidad quizás deberías especificar algunos requisitos sobre las entidades del problema. Ten en cuenta que lo recibirá otro estudiante que tendrá que saber qué código entregar para validar. Tienes una errata: "reglasformarán".

2024-10-10 21:12 UTC, eigenric commented on docs/milestones.md
> +## Milestone 2:
En este milestone está definido el objetivo pero no quedan claros los requisitos sobre el código entregable para su superación.
Le faltaría también una historia de usuario asociada.

2024-10-10 21:31 UTC, adiazcencillo commented
Buenas, se me ha asignado tu PR para revisar. Te comento algunos problemas que he encontrado

2024-10-11 08:04 UTC, MarioRgzLpz commented
Buenas, voy a ser uno de los revisores de esta PR. En general no esta del todo mal pero, hay algunos fallos de concepto que debes aclarar. A continuación te subrayo lo que he encontrado.

2024-10-11 08:08 UTC, MarioRgzLpz commented on docs/milestones.md
> +Analizar las historias de usuario y definir las reglas a tener en cuenta, así como las tecnologías que serán necesarias para comenzar y los objetos iniciales con los que se definirán las reglasformar
```suggestion
Analizar las historias de usuario y definir las reglas a tener en cuenta, así como las tecnologías que serán necesarias para comenzar y los objetos iniciales con los que se definirán las reglas que formarán parte y se tendrán en cuenta en la lógica de la aplicación (esquema sustantivo -> objeto).
```
Typo. Aunque podrías reformular un poco esto para que fuese más claro ya que es un poco confuso.

2024-10-11 08:15 UTC, MarioRgzLpz commented on docs/user_journeys.md
¿Porqué solo has añadido user jorneys para dos de los usuarios?

2024-10-11 08:17 UTC, MarioRgzLpz commented on docs/HU.md
En general las HUs descritas no estan del todo mal pero, en ninguna muestras el deseo de cada usuario. Esto es muy importante a la hora del desarrollo, para saber que es lo que queremos realizar y en donde debemos enfocarnos.

2024-10-11 08:22 UTC, MarioRgzLpz commented on docs/HU.md
Añadir a cada HU algo como: _Me gustaría, sería de utilidad..._

2024-10-11 08:25 UTC, MarioRgzLpz commented on README.md
La documentación y la configuración es recomendable que se encuentren en carpetas distintas ya que no son lo mismo. Esto deberías de hacerlo en tu rama main y luego hacer un rebase.

2024-10-11 08:28 UTC, MarioRgzLpz commented on docs/HU.md
También añade a cada issue la etiqueta `user-stories` para el futuro no perder de vista cuales son las HUs.

2024-10-11 10:32 UTC, adiazcencillo commented on docs/HU.md
> +## [[HU001] Manuel, rotatorio noches](https://github.com/abbonno/healthScheduler/issues/3)
Creo que entiendo el problema que quieres expresar en esta HU, pero lo veo algo ambiguo. Como se indica en la memoria del objetivo: _Los deseos de estos usuarios, es decir, los problemas que quieren que la aplicación les resuelva, se tienen que resumir en las historias de usuario._

2024-10-11 10:32 UTC, adiazcencillo commented on docs/milestones.md
> +Analizar las historias de usuario y definir las reglas a tener en cuenta, así como las tecnologías que serán necesarias para comenzar y los objetos iniciales con los que se definirán las reglasformar
El concepto regla en este caso lo veo un poco ambiguo. Creo que hay conceptos que describen mejor lo que se quiere conseguir con este milestone, y que por tanto ayudarían más al futuro desarrollador,  _reglas a tener en cuenta_ es algo poco claro. También creo que hablar de esquema sustantivo->objeto todavía es pronto, quizá más adelante. También puede ser intersante que refieras exactamente de qué problemas (HUs) quieres definir estas _reglas_, ya que las distintas HUs pueden tener diferentes aspectos del problema (échale un ojo al documento de errores frecuentes).

2024-10-11 10:32 UTC, adiazcencillo commented on docs/milestones.md
> +- Se define un objeto y/o atributos por cada aspecto a tener en cuenta en las historias de usuario (enfermero, contrato, turno, días libres...).
La descripción del entregable quizá es demasiado detallada. En este objetivo pretendemos establecer la estructura general, sin entrar en más detalle. Al añadir esta descripción, no se deja mucho margen al desarrollador. Esto también viene recogido en los errores frecuentes.

2024-10-18 11:06 UTC, abbonno commented on docs/milestones.md
> +## Milestone 2:
El profesor me ha comentado que no hace falta relacionar una historia de usuario a cada milestone. Como tampoco es necesario he eliminado el milestone 2 y a cambio he modificado un poco los otros. Gracias!

2024-10-18 11:07 UTC, abbonno commented on docs/HU.md
Dicho y hecho. Gracias!

2024-10-18 11:08 UTC, abbonno commented on docs/user_journeys.md
Considero que los user journeys que existen engloban bien las hipotéticas experiencias de los enfermeros.

2024-10-18 11:09 UTC, abbonno commented on docs/HU.md
> +## [[HU001] Manuel, rotatorio noches](https://github.com/abbonno/healthScheduler/issues/3)
He añadido unas sentencias al final de cada historia de usuario en las que creo que se expresa mejor lo que quiere cada uno.

2024-10-18 11:12 UTC, abbonno commented on docs/milestones.md
> +Analizar las historias de usuario y definir las reglas a tener en cuenta, así como las tecnologías que serán necesarias para comenzar y los objetos iniciales con los que se definirán las reglasformar
He cambiado algunas cosas, en caso que detectes algún problema más házmelo saber. Gracias!

2024-10-18 11:16 UTC, abbonno commented on docs/milestones.md
> +- Se define un objeto y/o atributos por cada aspecto a tener en cuenta en las historias de usuario (enfermero, contrato, turno, días libres...).
He modificado algunas cosas pero todavía no tengo claro del todo si cumplen con estos requisitos. Si tienes alguna objeción y supieras darme algún consejo coméntamelo también.

2024-10-18 12:02 UTC, MarioRgzLpz approved these changes

2024-10-24 12:02 UTC, abbonno commented
@jj

2024-10-24 12:07 UTC, juanbarearojo commented on docs/milestones.md
> +## Milestone 0: Análisis del problema y primer acercamiento
La estructura del milestone en sí la veo bien planteada. Has considerado plantear esta milestone como m1 en vez de m0. Lo digo porque para la futura realización de este es necesario plantear las bases que más adelante trabajarás sobre ellas.

2024-10-24 16:24 UTC, eigenric commented on docs/milestones.md
> +## Milestone 2:
Es cierto, hoy aprendí que poner historias de usuario asociadas es un error frecuente. Gracias!

2024-10-24 16:47 UTC, adiazcencillo reviewed
Te dejo algunas apreciaciones más que considero pertinentes.

2024-10-24 16:47 UTC, adiazcencillo commented on docs/milestones.md
> +Analizar las historias de usuario. Decidir las tecnologías que serán necesarias para comenzar a tratar el problema. Con respecto a la historia de usuario 1, plantear la manera de calcular los turnos
Échale un ojo a los errores frecuentes del objetivo 1. El segundo que se menciona es _poner "HUs asociadas"_. La explicación: 

_Aunque los milestones en principio no tienen por qué tener información sobre las historias de usuario, si hay varias historias de usuario hablar de "modelo del problema" o de "lógica de negocio" no es suficiente, porque las dos historias de usuario (o las 5) pueden tener diferentes aspectos del problema, o incluso ser problemas diferentes. En todo caso, siempre es conveniente ser preciso en el lenguaje, porque en el momento que se vaya a trabajar con un milestone determinado puede haber más historias de usuario, o menos, así que aclarar a qué parte del problema del cliente se circunscribe siempre es conveniente.

De la misma forma, enlazar todas las historias de usuario sólo indica dejadez y falta de precisión a la hora de indicar a la persona que trabaje qué es lo que debe hacer._

También considero que debes especificar qué quieres hacer con ese análisis, debe materializarse en algo tangible (un PMV).

2024-10-24 16:47 UTC, adiazcencillo commented on docs/milestones.md
> ++ **Mínimo viable**
Te enlazo otro de los problemas frecuentes recogidos en el archivo correspondiente:

_Por favor, no inventéis y pidáis cosas que no vienen a cuento ni sirven realmente para nada. Estoy pensando en pedir "documentos" con el modelo del problema, pero no descarto que metáis diagramas UML o alguna otra cosa igualmente inútil. Un producto es código funcionando, y que siga algún criterio de viabilidad. Punto._

En resumen: el PMV debe ser código.

2024-10-24 16:57 UTC, eigenric commented
Buenas, veo en general que los cambios realizados aclaran bastante los milestones con respecto al primer acercamiento. Te dejo un comentario relativo a los user-journeys que te puede ser de utilidad.

2024-10-24 16:58 UTC, eigenric commented on docs/user_journeys.md
> +
En el documento de errores frecuentes se dice lo siguiente "Los user journeys sirven principalmente para añadir detalle y contexto a las historias de usuario. Por lo tanto, ponerlos de forma independiente sin ningún enlace con las mismas les priva de utilidad."

2024-10-25 11:23 UTC, abbonno commented on docs/milestones.md
> +## Milestone 0: Análisis del problema y primer acercamiento
Tienes razón, he modificado los milestones 0 y 1 y he añadido un m2 como resultado de la modificación.
He creado el siguiente commit para la corrección: [a4fb3c7]

2024-10-25 11:24 UTC, abbonno commented on docs/milestones.md
> +Analizar las historias de usuario. Decidir las tecnologías que serán necesarias para comenzar a tratar el problema. Con respecto a la historia de usuario 1, plantear la manera de calcular los turnos
He asociado las historias de usuario de una forma algo más descriptiva. [285c724]

2024-10-25 11:27 UTC, abbonno commented on docs/user_journeys.md
> +
He descrito brevemente con qué historias de usuario se enlazan los user journeys. Considero que aunque un user journey sea descrito a partir de una historia de usuario puede definir bien la experiencia de otros usuarios y crear otros user journeys para ellos es redundante. [c754024]

2024-10-25 11:56 UTC, JJ requested changes
Y por favor, leed los errores frecuentes...

2024-10-25 11:56 UTC, JJ commented on docs/milestones.md
> +## Milestone 0: Análisis del problema y primer acercamiento
¿Análisis describe un producto o una tarea?

2024-10-25 11:56 UTC, JJ commented on docs/milestones.md
> +Analizar las historias de usuario. Decidir las tecnologías que serán necesarias para comenzar a tratar el problema. Con respecto a la historia de usuario 1, definir las entidades y objetos comprendid
Ya hemos quedado que "analizar" no describe un producto. Pero además, haces referencia a *todas* las historias de usuario.

2024-10-25 11:56 UTC, JJ commented on docs/milestones.md
> +- Se ha escogido un lenguaje y una estructura de directorios adecuados para afrontar el proyecto.
Esto va implícito.

2024-10-25 11:56 UTC, JJ commented on docs/milestones.md
> +- Existe una estructura para cada entidad básica del problema (una clase, un objeto, una variable, una constante, un struct...).
No solo una estructura. Un modelo incluye más cosas.

2024-10-25 11:56 UTC, JJ commented on docs/milestones.md
> +## Milestone 1: Creación horario inicial
Los productos se enuncian de forma genérica. Si dices qué forma vas a tener, estás cerrando el proceso de desarrollo.

2024-11-07 11:40 UTC, abbonno commented
@JJ

2024-11-07 11:46 UTC, abbonno commented on docs/milestones.md
> +## Milestone 1: Creación horario inicial
Resuelto en [04935c8], con una propuesta menos específica.

2024-11-07 11:54 UTC, abbonno commented on docs/milestones.md
> +- Se ha escogido un lenguaje y una estructura de directorios adecuados para afrontar el proyecto.
[0f2d026]

2024-11-07 11:54 UTC, abbonno commented on docs/milestones.md
> +- Existe una estructura para cada entidad básica del problema (una clase, un objeto, una variable, una constante, un struct...).
[0f2d026]

2024-11-07 11:54 UTC, abbonno commented on docs/milestones.md
> +## Milestone 0: Análisis del problema y primer acercamiento
[04935c8]

2024-11-07 12:08 UTC, JJ requested changes
Ni la HU ni el milestone deben especificar soluciones, sólo cómo reconocer la solución correcta.

2024-11-07 12:08 UTC, JJ commented on docs/milestones.md
> +- Existe una estructura para cada entidad básica del problema (una clase, un objeto, una variable, una constante, un struct...), así como las relaciones que existen entre ellas.
Pero ¿por qué lo especificas? ¿No crees que la persona que lo programe ya sabrá si es una clase o un objeto o un qué?

2024-11-07 12:08 UTC, JJ commented on docs/milestones.md
> +- Se define un algoritmo de asignación equilibrada de turnos, dado un número de trabajadores.
¿Esto viene en la hU correspondiente? Si viene, ¿por qué lo dices aquí? Si no viene, ¿no crees que debería estar en la HU todos los factores del problema? En todo caos, ni aquí ni en una hU debe haber soluciones, solo referencias a problemas.

2024-11-07 12:14 UTC, abbonno commented on docs/milestones.md
> +- Existe una estructura para cada entidad básica del problema (una clase, un objeto, una variable, una constante, un struct...), así como las relaciones que existen entre ellas.
[218ef28]

2024-11-07 12:14 UTC, abbonno commented on docs/milestones.md
> +- Se define un algoritmo de asignación equilibrada de turnos, dado un número de trabajadores.
[218ef28]

2024-11-07 12:19 UTC, abbonno commented
@JJ

2024-11-07 12:19 UTC, abbonno commented
@JJ

2024-11-07 13:11 UTC, abbonno commented
@JJ

2024-11-07 13:18 UTC, abbonno commented
@JJ

2024-11-07 13:24 UTC, abbonno commented
@JJ

2024-11-07 13:26 UTC, JJ approved these changes
Lo que te sirva de las UJ lo añades a las HU. Estas deben contener todo lo necesario para trabajar.

2024-11-07 13:27 UTC, merged